// Game constants (Node.js module)
const CANVAS_W = 800;
const CANVAS_H = 500;

const PADDLE_W = 12;
const PADDLE_H = 90;
const PADDLE_SPEED = 6;

const BALL_SIZE = 10;
const BALL_SPEED_INIT = 5;
const BALL_SPEED_MAX = 12;

const WIN_SCORE = 10;

const ROUND_TIME_LIMIT = 60000;

const SLOW_COOLDOWN = 5000;
const SLOW_DURATION = 5000;

const PLAYER_SLOW_DELAY = 10000;

const COUNTDOWN_DURATION = 3000;

const EXPLOSION_DURATION = 1000;

const TRAIL_MAX = 20;

module.exports = {
    CANVAS_W,
    CANVAS_H,
    PADDLE_W,
    PADDLE_H,
    PADDLE_SPEED,
    BALL_SIZE,
    BALL_SPEED_INIT,
    BALL_SPEED_MAX,
    WIN_SCORE,
    ROUND_TIME_LIMIT,
    SLOW_COOLDOWN,
    SLOW_DURATION,
    PLAYER_SLOW_DELAY,
    COUNTDOWN_DURATION,
    EXPLOSION_DURATION,
    TRAIL_MAX,
};
